## 線形代数の基本

### ベクトルと内積

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([1, 1, 1, 1])

In [2]:
result = 0

for a_val, b_val in zip(a, b):
    result += a_val * b_val

result

10

In [3]:
a.dot(b)

10

In [4]:
a @ b

10

In [5]:
c = np.array([1, -1, -1, 1])
a @ c

0

In [6]:
np.linalg.norm(b)

2.0

In [7]:
unit_b = b / np.linalg.norm(b)
np.linalg.norm(unit_b)

1.0

### 行列

In [8]:
A = np.array([[0, 1, 2], [-1, 0, 1]])
A

array([[ 0,  1,  2],
       [-1,  0,  1]])

In [9]:
A.shape

(2, 3)

In [10]:
A.T

array([[ 0, -1],
       [ 1,  0],
       [ 2,  1]])

In [11]:
# 各要素の2倍
2 * A

array([[ 0,  2,  4],
       [-2,  0,  2]])

In [12]:
# 要素同士の足し算
A + A

array([[ 0,  2,  4],
       [-2,  0,  2]])

In [13]:
A @ A.T

array([[5, 2],
       [2, 2]])

In [14]:
A.T @ A

array([[ 1,  0, -1],
       [ 0,  1,  2],
       [-1,  2,  5]])

### 転置行列とその性質

In [15]:
X = A
Y = A.T
X @ Y

array([[5, 2],
       [2, 2]])

In [16]:
Y.T @ X.T

array([[5, 2],
       [2, 2]])

In [17]:
r2 = np.sqrt(2.0)
V = np.array(
    [
        [-1 / r2, -1 / r2],
        [1 / r2, -1 / r2],
    ]
)
# 1列目と2列目は直交（内積が0）
V[:, 0] @ V[:, 1]

0.0

In [18]:
# ノルムは1（表示は浮動小数点演算の誤差のため1になっていない）
np.linalg.norm(V[:, 0])

0.9999999999999999

In [19]:
# 2行2列の単位行列になる
V.T @ V

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])

### 行列とベクトル

In [20]:
# A = np.array([[0, 1, 2], [-1, 0, 1]])
A[0]

array([0, 1, 2])

In [21]:
A[0].reshape(1, -1)

array([[0, 1, 2]])

In [22]:
# 1列をとってくる
A[:, 0]

array([ 0, -1])

In [23]:
# 列ベクトルにする
A[:, 0].reshape(-1, 1)

array([[ 0],
       [-1]])

In [24]:
# 行ベクトル
row_vec3 = np.array([[1, 1, 1]])
# 列ベクトル
col_vec3 = np.array([[1], [1], [1]])

In [25]:
# サイズが違う
print(row_vec3.shape, col_vec3.shape)

(1, 3) (3, 1)


In [26]:
# 行列との掛け算
A @ col_vec3

array([[3],
       [0]])

In [27]:
# Aの列数が3、row_vecの行数が1で一致しないため掛け算できない
A @ row_vec3

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [28]:
# 行ベクトル
row_vec2 = np.array([[1, 1]])
# 列ベクトル
col_vec2 = np.array([[1], [1]])

In [29]:
# 1行2列ｘ2行3列なので計算できる
row_vec2 @ A

array([[-1,  1,  3]])

In [30]:
# 2行1列ｘ2行3列なので計算できない
col_vec2 @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [31]:
# 行ベクトルとして計算を実行してくれる
np.array([1, 1]) @ A

array([-1,  1,  3])

In [32]:
# 列ベクトルとして計算を実行してくれる
A @ np.array([1, 1, 1])

array([3, 0])

### 行列のランク

In [33]:
np.linalg.matrix_rank(A)

2

In [34]:
# 別の行列Bを用意してランクを計算
B = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 0]])
np.linalg.matrix_rank(B)

3

In [36]:
M = np.array([[-1], [1], [0.5]]) @ np.array([[2, 4, 6]])
M

array([[-2., -4., -6.],
       [ 2.,  4.,  6.],
       [ 1.,  2.,  3.]])

In [37]:
np.linalg.matrix_rank(M)

1

### 固有値と固有ベクトル

In [38]:
D = A @ A.T
D

array([[5, 2],
       [2, 2]])

In [39]:
# 2組の固有値と固有ベクトルが求まります
r, X = np.linalg.eig(D)

In [48]:
# 2つの固有値
r

array([6., 1.])

In [49]:
# 対応する固有ベクトル
X

array([[ 0.89442719, -0.4472136 ],
       [ 0.4472136 ,  0.89442719]])

In [40]:
# 1つ目の固有ベクトルを取り出します
x = X[:, 0]
D @ x == r[0] * x

array([ True,  True])