## 数値データの型
### NumPyの数値データ型

In [1]:
import numpy as np

np.array([1, 2, 3], dtype=np.byte)

array([1, 2, 3], dtype=int8)

In [2]:
np.array([1, 2, 3], dtype=np.int8)

array([1, 2, 3], dtype=int8)

In [3]:
np.array([1, 2, 3], dtype="byte")

array([1, 2, 3], dtype=int8)

In [4]:
np.array([1, 2, 3], dtype="int8")

array([1, 2, 3], dtype=int8)

In [5]:
np.array([1, 2, 3], dtype="b")

array([1, 2, 3], dtype=int8)

In [6]:
i_num = np.uint8(128)
print(
    i_num,
    type(i_num),
    i_num.dtype,
    sep="\n",
)

128
<class 'numpy.uint8'>
uint8


In [7]:
f_num = np.single("0.25")
print(
    f_num,
    type(f_num),
    f_num.dtype,
    sep="\n",
)

0.25
<class 'numpy.float32'>
float32


In [8]:
# 32ビット符号付き整数の最大値と最小値
print(np.iinfo(np.intc))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------



In [9]:
# 64ビット浮動小数点数の情報
print(np.finfo(np.double))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------



### 数値の演算と型の変換

In [10]:
# intにnumpy.int64が対応する例
i_array = np.array([1, 2, 3])
print(i_array.dtype)

int64


In [11]:
# 組み込み型のfloatはnumpy.float64
f_array = np.array([1.0, 2.0, 3.0])
print(f_array.dtype)

float64


In [12]:
# 組み込み型のcomplexはnumpy.complex128
c_array = np.array([1j, 2j, 3j])
print(c_array.dtype)

complex128


In [13]:
f_array = np.array([0.5, -1.2, 8.9], dtype=np.double)
f_array.astype(np.int64)

array([ 0, -1,  8])

In [14]:
# 0-1が255になってしまう。
a = np.uint8(0)
b = np.uint8(1)
a - b

/var/folders/gg/y144ms9d1l51khjw847lxkb80000gn/T/ipykernel_16640/2114708084.py:4: RuntimeWarning: overflow encountered in ubyte_scalars
  a - b


255

In [15]:
# 255+1が0になってしまう
a = np.uint8(255)
b = np.uint8(1)
a + b

/var/folders/gg/y144ms9d1l51khjw847lxkb80000gn/T/ipykernel_16640/140568556.py:4: RuntimeWarning: overflow encountered in ubyte_scalars
  a + b


0

In [16]:
np.array([0, 255], dtype=np.uint8) + np.array([-1, 1], dtype=np.int32)

array([ -1, 256], dtype=int32)

In [17]:
# 1の後ろに0が20個並ぶ数になる
10**20

100000000000000000000

In [18]:
# 正しい結果が得られない
np.power(10, 20, dtype=np.int64)

7766279631452241920

In [19]:
np.power(10, 20, dtype=np.float32)

1e+20

In [20]:
np.power(10, 100, dtype=np.float32)

/var/folders/gg/y144ms9d1l51khjw847lxkb80000gn/T/ipykernel_16640/1215880753.py:1: RuntimeWarning: overflow encountered in power
  np.power(10, 100, dtype=np.float32)


inf

In [21]:
np.divide(np.inf, np.inf)

/var/folders/gg/y144ms9d1l51khjw847lxkb80000gn/T/ipykernel_16640/3650871706.py:1: RuntimeWarning: invalid value encountered in divide
  np.divide(np.inf, np.inf)


nan