## 配列の構造とブロードキャスト

### 配列の形状を変える

In [1]:
import numpy as np

elm_12 = np.arange(12)
elm_12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
elm_12.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
np.reshape(elm_12, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [4]:
# 12個の要素があるので、2×5には変形できない
elm_12.reshape(2, 5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [5]:
elm_12.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
elm_12.reshape(-1, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [7]:
elm_12.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [8]:
elm_12.reshape(1, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [9]:
elm_12.reshape(2, 1, 6)

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]]])

In [10]:
elm_12[np.newaxis]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [11]:
elm_12[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [12]:
np.newaxis is None

True

### ブロードキャスト

In [13]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
a + b

array([3, 5, 7])

In [14]:
c = np.array([-1, -2])
a + c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [15]:
a + 2

array([2, 3, 4])

In [16]:
# [[ 0,  1,  2,  3],
#  [ 4,  5,  6,  7], + [0, 1, 2, 3]
#  [ 8,  9, 10, 11]]
elm_12.reshape(3, 4) + np.array([0, 1, 2, 3])

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [16]:
elm_12.reshape(3, 4) + np.array([0, 1, 2])

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [18]:
# [[ 0,  1,  2,  3],   [0]
#  [ 4,  5,  6,  7], + [1]
#  [ 8,  9, 10, 11]]   [2]
elm_12.reshape(3, 4) + np.array([0, 1, 2]).reshape(-1, 1)

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [19]:
# a -> [[0, 1, 2]]
# b -> [[3], [4], [5]]
a[np.newaxis, :] + b[:, np.newaxis]

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])